### ISSUE TITLE
Can't make it to work

### ISSUE THREAD

**Issue by moelheni** [Genymobile/aws-ssl#1]
So we have a Genymotion instance, a certificate for the domain *.example.com and the authority certificate and the Key we used in the creation of the instance, we used Route53 to give the instance a DNS. 

Reading the readme I didn't get how to get all those params like "kspassword" "kppassword" and <relpath_to_fullchain.pem>

**Comment by ivan133** [comment]
I don't understand - so I can't use letsenscypt now?
Looks like it was removed on this commit b89a4a1

**Comment by jcleneveu-geny** [comment]
Hi @ivan133,

Thank you for using our product! I confirm that this commit removed the let's encrypt script because it is not needed anymore as the generation is now bundled the inside the VM to be easier to use. You can find the updated documentation here => https://www.genymotion.com/help/cloud-paas/tutorial/install-auto-generated-certificate/

With this new changes, this repository should only be used to transfer an existing certificate to the Genymotion VM. Feel free to ask for help if you have any more question by using our support page: https://www.genymotion.com/help/cloud-paas/support/

**Comment by jcleneveu-geny** [comment]
@insatmc if you still have the issue, feel free to query the support (https://www.genymotion.com/help/cloud-paas/support/), if not we will close this ticket within a week.
