### ISSUE TITLE
Executed everything but i still have the original genymotion server certificate

### ISSUE THREAD

**Issue by GhaziBenDahmane** [Genymobile/aws-ssl#2]
I succeeded to execute everything without errors but my certificate was not changed

**Comment by Teketel** [comment]
I am facing the same issue, please help me.

**Comment by GhaziBenDahmane** [comment]
check your security group to be sure you have access for port 5555 , then adb connect *ip-here* and be sure this connection didn't fail aka you have no "unable to connect to xxxxxxxxxx:5555" .
make sure you copied the correct files with fullchain.pem being your certificate file and priv.pem being your private key , make sure you have the correct version of jre , and repeat until it works ( this is literally how it worked for me ... , i repeated the process ~10 times on different instances until it worked )

**Comment by jcleneveu-geny** [comment]
Hi guys,

This issue looks outdated so I'll close it. Feel free to reopen if you are still affected by this issue. Please also note that since this ticket was created the procedure changed and you can find the new tutorial here => https://www.genymotion.com/help/cloud-paas/tutorial/install-auto-generated-certificate/

Jc
